version: '3.1'

services:

  mysql:
    image: mysql
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Bangkok
    ports:
      - 3306:3306
    networks:
      - back

  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports: 
      - 1883:1883 
      - 9001:9001
    environment:
      TZ: "Asia/Bangkok"
    networks:
      - back

  nodered:
    build:
      context: .
      dockerfile: Dockerfile_NodeRed
    restart: always
    ports: 
      - 1880:1880 
    environment:
      TZ: "Asia/Bangkok"
    networks:
      - back
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - 80:80
    environment:
      PMA_HOST: mysql
      TZ: "Asia/Bangkok"
    networks:
      - back

networks:
  back:
    
